spring:
  datasource:
    url: jdbc:postgresql://localhost:6432/guruDB?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      default_schema: public
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
    enabled: true

server:
  port: 8082

telegram:
  token: ${TELEGRAM_TOKEN}

ai:
  token: ${AI_TOKEN}