spring:
  datasource:
    url: jdbc:postgresql://localhost:6432/guruDB?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: org.postgresql.Driver
    username: guru
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      default_schema: public
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
    enabled: true

server:
  port: 8082

telegram:
  token: 7114928829:AAH0Cln9m0nsL2Y9RKb4n_qLjpY378869z4